FROM golang:latest as builder

LABEL maintainer="Eddy Moulton <eddymoulton@gmail.com>"
ADD VERSION .

RUN mkdir /build
ADD . /build/
WORKDIR /build
RUN CGO_ENABLED=1 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main ./cmd/voltrack-api

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /build/main /app/
WORKDIR /app
CMD ["./main"]
