version: "3.7"
services:
  api:
    container_name: voltrack_api
    environment:
      DB_HOST: "10.1.1.8"
      DB_PORT: "5434"
      DB_PASSWORD: "password"
      ENV_DEVELOPMENT: "true"
    build:
      context: ./
      dockerfile: build/dockerfile.api.development
    ports:
      - "3000:3000"
    volumes:
      - ./:/app

  web:
    container_name: voltrack_web
    build:
      context: .
      target: "develop-stage"
      dockerfile: build/dockerfile.web
    ports:
      - "8080:8080"
    volumes:
      - "./web:/app"
    command: /bin/sh -c "yarn serve"

  sql:
    container_name: voltrack_sql
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./temp/postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
