// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/eddymoulton/stock-tracker/cmd/stocktracker/transactions"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

// Injectors from wire.go:

func InitTransactionAPI(db2 *gorm.DB) transactions.TransactionAPI {
	transactionRepository := transactions.ProvideTransactionRepository(db2)
	transactionService := transactions.ProvideTransactionService(transactionRepository)
	transactionAPI := transactions.ProvideTransactionAPI(transactionService)
	return transactionAPI
}
