// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/eddymoulton/stock-tracker/cmd/stocktracker/logger"
	"github.com/eddymoulton/stock-tracker/cmd/stocktracker/stocks"
	"github.com/eddymoulton/stock-tracker/cmd/stocktracker/transactions"
	"github.com/jinzhu/gorm"
)

import (
	_ "github.com/jinzhu/gorm/dialects/sqlite"
)

// Injectors from wire.go:

func InitTransactionAPI(db2 *gorm.DB, logger2 *logger.Logger) transactions.TransactionAPI {
	transactionRepository := transactions.ProvideTransactionRepository(db2, logger2)
	stocksRepository := stocks.ProvideStocksRepository(db2)
	stocksService := stocks.ProvideStocksService(stocksRepository)
	transactionService := transactions.ProvideTransactionService(transactionRepository, stocksService)
	transactionAPI := transactions.ProvideTransactionAPI(transactionService)
	return transactionAPI
}
