@base_url = http://localhost:3000/api

### Life test
GET {{base_url}}

### Post transaction
POST {{base_url}}/stocks/transactions
content-type: application/json

{
	"buySell" : 1,
	"date" : "2020-02-08T22:08:00Z",
	"cost" : 19500,
	"fee" : 100000,
	"stockCode" : "AA1",
    "quantity" : 1
}

### Get Transactions
GET {{base_url}}/stocks/transactions