@base_url = http://localhost:3000/api

### Life test
GET {{base_url}}

### Buy stocks
POST {{base_url}}/stocks/transactions
content-type: application/json

{
	"buySell" : 1,
	"date" : "2020-01-08T22:08:00Z",
	"cost" : 19500,
	"fee" : 100000,
	"stockCode" : "VGS",
    "quantity" : 10
}

### Sell stock
POST {{base_url}}/stocks/transactions
content-type: application/json

{
	"buySell" : -1,
	"date" : "2020-03-08T22:08:00Z",
	"cost" : 19500,
	"fee" : 100000,
	"stockCode" : "VGS",
    "quantity" : 5
}

### Generate Reports
PUT {{base_url}}/reporting/generate
content-type: application/json

{
	"start" : "2020-02-07T22:08:00Z",
	"end" : "2020-02-13T22:08:00Z"
}

### Get Reports
GET {{base_url}}/stocks/history
content-type: application/json

{
	"stockCodes" : ["VGS", "AGR"],
	"start" : "2020-02-07T22:08:00Z",
	"end" : "2020-02-13T22:08:00Z"
}

### Get Transactions
GET {{base_url}}/stocks/transactions

### Get Stocks
GET {{base_url}}/stocks

### Get Current Stocks
GET {{base_url}}/stocks/current